import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import os from 'node:os';import path from 'node:path';import {generateKeyPairSync,sign,randomUUID} from 'node:crypto';
import {PRODUCT,fingerprint,validateLicense,createLicenseGuard} from '../desktop/license.mjs';import {openStore} from '../desktop/store.mjs';import {createApi} from '../desktop/api.mjs';import {filterPayments,collectedTotal} from '../lib/payment-filters.ts';
const keys=generateKeyPairSync('ed25519');const publicKey=keys.publicKey.export({type:'spki',format:'pem'});const machine=fingerprint(['windows','hardware-id-one']);
function issue(extra={},key=keys.privateKey){const claims={product:PRODUCT,licenseId:randomUUID(),customer:'Test Customer',machine,issuedAt:Date.now()-1000,notBefore:Date.now()-1000,expiresAt:null,...extra};const bytes=Buffer.from(JSON.stringify(claims));return JSON.stringify({version:1,payload:bytes.toString('base64url'),signature:sign(null,bytes,key).toString('base64url')});}
test('method filters cover all methods and sum in integer paise',()=>{const payments=['Cash','UPI','Card','Bank transfer'].flatMap((method,i)=>[{id:String(i),memberId:'m',method,date:'2026-09-01',amount:10.1,note:''},{id:String(i)+'b',memberId:'m',method,date:'2026-08-01',amount:0.2,note:''}]);assert.equal(filterPayments(payments,'All').length,8);for(const method of ['Cash','UPI','Card','Bank transfer']){assert.equal(collectedTotal(filterPayments(payments,method)),10.3);assert.equal(collectedTotal(filterPayments(payments,method,'2026-09-01','2026-09-30')),10.1)}assert.equal(collectedTotal(filterPayments(payments,'UPI','2030-01-01')),0)});
test('signed license matches only correct machine and issuer',()=>{assert.equal(validateLicense(issue(),publicKey,machine).customer,'Test Customer');assert.throws(()=>validateLicense(issue(),publicKey,fingerprint(['windows','another-machine'])));const fake=generateKeyPairSync('ed25519');assert.throws(()=>validateLicense(issue({},fake.privateKey),publicKey,machine));});
test('tampering, expired license, future license and wrong product rejected',()=>{const l=JSON.parse(issue());l.payload=Buffer.from(JSON.stringify({machine})).toString('base64url');assert.throws(()=>validateLicense(JSON.stringify(l),publicKey,machine));for(const claims of [{expiresAt:Date.now()-1},{notBefore:Date.now()+3600000},{product:'different-product'}])assert.throws(()=>validateLicense(issue(claims),publicKey,machine));});
test('clock rollback fails closed; activation cannot reset it',()=>{let now=Date.now(),stored=issue(),seen=now;const guard=createLicenseGuard({publicKey,deviceId:machine,readLicense:()=>stored,writeLicense:v=>stored=v,readLastSeen:()=>seen,writeLastSeen:v=>seen=v,now:()=>now});guard.assertValid();now-=600000;assert.throws(()=>guard.assertValid(),/backwards/);assert.throws(()=>guard.activate(issue()),/clock/)});
test('licensed desktop API handles clean setup, auth, finance, roles, photos and restores',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'ironpulse-desktop-test-'));const store=openStore(path.join(dir,'gym.sqlite'));let licenseText='';const guard=createLicenseGuard({publicKey,deviceId:machine,readLicense:()=>licenseText,writeLicense:v=>licenseText=v,readLastSeen:()=>store.getMeta('seen'),writeLastSeen:v=>store.setMeta('seen',v)});const api=createApi(store,guard);try{
 const call=(url,method='GET',body={},session='')=>api.dispatch(url,method,body,session);
 assert.equal(call('/api/gym').status,423);assert.equal(call('/api/setup','POST',{name:'Unauthorized',email:'u@x.test',password:'strong-password'}).status,423);assert.equal(call('/api/license','POST',{license:issue()}).status,200);
 assert.equal(call('/api/setup').data.required,true);assert.equal(call('/api/setup','POST',{name:'Gym Owner',email:'owner@example.test',password:'Owner-Password-123',role:'Staff'}).status,201);assert.equal(call('/api/setup','POST',{}).status,409);assert.equal(call('/api/gym').status,401);
 const login=call('/api/auth/login','POST',{email:'owner@example.test',password:'Owner-Password-123'});assert.equal(login.status,200);const token=login.session;assert.equal(login.data.user.role,'Admin');let state=call('/api/gym','GET',{},token).data;assert.equal(state.data.members.length+state.data.plans.length+state.data.payments.length,0);
 const mutate=(action,value,id,expected=200,who=token,version=state.version)=>{const r=call('/api/gym','POST',{action,value,id,version},who);assert.equal(r.status,expected,JSON.stringify(r));if(r.status===200)state=r.data;return r};
 mutate('plan',{name:'Monthly',months:1,price:1000,description:''});let plan=state.data.plans[0];const today=new Date().toISOString().slice(0,10);const end=new Date(Date.now()+30*86400000).toISOString().slice(0,10);
 mutate('member',{name:'Test Member',email:'member@example.test',phone:'9876543210',emergency:'',planId:plan.id,start:today,end,due:today,fee:1000,notes:'',photo:''});const member=state.data.members[0];mutate('plan',{...plan,price:1200});assert.equal(state.data.members[0].fee,1000);
 for(const method of ['Cash','UPI','Card','Bank transfer'])mutate('payment',{memberId:member.id,date:today,method,amount:100,note:''});assert.equal(state.data.payments.length,4);mutate('payment',{memberId:member.id,date:today,method:'Cash',amount:601,note:''},null,400);
 mutate('attendance',null,member.id);mutate('attendance',null,member.id,400);mutate('settings',state.data.settings,null,409,token,state.version-1);
 const png={type:'image/png',base64:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jD1sAAAAASUVORK5CYII='};const photo=call('/api/photo','POST',png,token);assert.equal(photo.status,200);assert.equal(call(photo.data.url,'GET',{},token).data.base64,png.base64);mutate('member',{...member,photo:photo.data.url});
 const backup=call('/api/backup','GET',{},token).data;assert.equal(backup.photos.length,1);mutate('restore',backup);
 assert.equal(call('/api/users','POST',{name:'Staff User',email:'staff@example.test',password:'Staff-Password-123',role:'Staff'},token).status,201);const staff=call('/api/auth/login','POST',{email:'staff@example.test',password:'Staff-Password-123'}).session;for(const action of ['plan','settings','delete','restore'])mutate(action,{},member.id,403,staff);
 assert.equal(call('/api/backup','GET',{},staff).status,403);assert.equal(call('/api/users','POST',{},staff).status,403);mutate('payment',{memberId:member.id,date:today,method:'Cash',amount:100,note:''},null,200,staff);
 const before=store.snapshot();const bad={...backup,data:{...backup.data,members:[]}};mutate('restore',bad,null,400);assert.deepEqual(store.snapshot(),before);
 licenseText=issue({expiresAt:Date.now()-1});assert.equal(call('/api/gym','GET',{},token).status,423);assert.equal(call(photo.data.url,'GET',{},token).status,423);licenseText=issue();assert.equal(call('/api/gym','GET',{},token).status,401);
 const newToken=call('/api/auth/login','POST',{email:'owner@example.test',password:'Owner-Password-123'}).session;assert.equal(call('/api/auth/logout','POST',{},newToken).status,200);assert.equal(call('/api/gym','GET',{},newToken).status,401);
 }finally{api.close();rmSync(dir,{recursive:true,force:true})}});
test('local data survives process-level database close and reopen',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'ironpulse-persist-test-'));const file=path.join(dir,'db.sqlite');let store=openStore(file);store.setMeta('test','saved');store.close();store=openStore(file);assert.equal(store.getMeta('test'),'saved');store.close();rmSync(dir,{recursive:true,force:true})});
