import express from 'express';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import cookieParser from 'cookie-parser';
import multer from 'multer';
import { randomUUID } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { emptyGym } from '../lib/gym.ts';
import { applyMutation } from '../lib/gym-operations.ts';

const production=process.env.NODE_ENV==='production';
const {MONGODB_URI,JWT_SECRET}=process.env;
if(!MONGODB_URI||!JWT_SECRET||JWT_SECRET.length<48)throw Error('Set MONGODB_URI and a random JWT_SECRET of at least 48 characters.');
if(process.env.SEED_DEMO==='true')throw Error('Demo seeding is disabled in this local release. Remove SEED_DEMO.');
const app=express();
if(process.env.TRUST_PROXY_HOPS)app.set('trust proxy',Number(process.env.TRUST_PROXY_HOPS));
app.disable('x-powered-by');
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:','blob:'],connectSrc:["'self'"],fontSrc:["'self'"],objectSrc:["'none'"],baseUri:["'self'"],frameAncestors:["'none'"],upgradeInsecureRequests:production?[]:null}}}));
app.use(express.json({limit:'12mb'}));app.use(cookieParser());
const origin=process.env.APP_ORIGIN||'http://localhost:3000';
app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.get('origin')!==origin)return res.status(403).json({error:'Invalid request origin'});next()});
app.use('/api',rateLimit({windowMs:60000,limit:180,standardHeaders:'draft-8',legacyHeaders:false}));
const userSchema=new mongoose.Schema({email:{type:String,unique:true,required:true},name:{type:String,required:true},passwordHash:{type:String,required:true,select:false},role:{type:String,enum:['Admin','Staff'],required:true},gymId:{type:String,required:true},tokenVersion:{type:Number,default:0}},{timestamps:true});
const User=mongoose.model('User',userSchema);
const State=mongoose.model('GymState',new mongoose.Schema({gymId:{type:String,unique:true,required:true},payload:{type:mongoose.Schema.Types.Mixed,required:true},version:{type:Number,default:1}},{timestamps:true}));
await mongoose.connect(MONGODB_URI,{serverSelectionTimeoutMS:10000});await Promise.all([User.init(),State.init()]);
const gymId=process.env.GYM_ID||'ironpulse';
if(!await User.exists({gymId,role:'Admin'})){
 const email=process.env.ADMIN_EMAIL;const password=process.env.ADMIN_PASSWORD;
 if(!email||!/^\S+@\S+\.\S+$/.test(email)||!password||password.length<12||Buffer.byteLength(password)>72)throw Error('Set ADMIN_EMAIL and ADMIN_PASSWORD (at least 12 characters) to provision the first admin.');
 await User.create({email:email.toLowerCase(),name:process.env.ADMIN_NAME||'Gym Admin',passwordHash:await bcrypt.hash(password,12),role:'Admin',gymId});
}
if(!await State.exists({gymId}))await State.create({gymId,payload:emptyGym(),version:1});
const bucket=new mongoose.mongo.GridFSBucket(mongoose.connection.db,{bucketName:'photos'});
const cookieOptions={httpOnly:true,secure:production,sameSite:'strict',path:'/api',maxAge:8*60*60*1000};
const auth=async(req,res,next)=>{try{const claims=jwt.verify(req.cookies.gym_session,JWT_SECRET,{algorithms:['HS256'],issuer:'ironpulse',audience:'ironpulse-web'});const user=await User.findById(claims.sub).lean();if(!user||user.tokenVersion!==claims.ver)throw Error();req.user=user;next()}catch{return res.status(401).json({error:'Please sign in to continue.'})}};
const admin=(req,res,next)=>req.user.role==='Admin'?next():res.status(403).json({error:'Administrator access is required.'});
const loginLimiter=rateLimit({windowMs:15*60000,limit:10,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'Too many sign-in attempts. Try again in 15 minutes.'}});
const dummyHash=await bcrypt.hash(randomUUID(),12);
app.post('/api/auth/login',loginLimiter,async(req,res)=>{const {email,password}=req.body||{};if(typeof email!=='string'||typeof password!=='string'||email.length>254||Buffer.byteLength(password)>72)return res.status(400).json({error:'Enter a valid email and password.'});const user=await User.findOne({email:email.toLowerCase().trim()}).select('+passwordHash');const match=await bcrypt.compare(password,user?.passwordHash||dummyHash);if(!user||!match)return res.status(401).json({error:'Email or password is incorrect.'});const token=jwt.sign({ver:user.tokenVersion},JWT_SECRET,{algorithm:'HS256',subject:String(user._id),issuer:'ironpulse',audience:'ironpulse-web',expiresIn:'8h'});res.cookie('gym_session',token,cookieOptions).json({user:{email:user.email,name:user.name,role:user.role}})});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:{email:req.user.email,name:req.user.name,role:req.user.role}}));
app.post('/api/auth/logout',auth,async(req,res)=>{await User.updateOne({_id:req.user._id},{$inc:{tokenVersion:1}});res.clearCookie('gym_session',{...cookieOptions,maxAge:undefined}).json({ok:true})});
app.get('/api/users',auth,admin,async(req,res)=>res.json({users:await User.find({gymId:req.user.gymId}).select('email name role').lean()}));
app.post('/api/users',auth,admin,async(req,res)=>{const {email,name,password,role}=req.body||{};if(typeof email!=='string'||!/^\S+@\S+\.\S+$/.test(email)||email.length>254||typeof name!=='string'||name.length<2||name.length>80||typeof password!=='string'||password.length<12||Buffer.byteLength(password)>72||!['Admin','Staff'].includes(role))return res.status(400).json({error:'Use a valid email, name, role and a password of at least 12 characters (maximum 72 UTF-8 bytes).'});try{await User.create({email:email.toLowerCase().trim(),name,passwordHash:await bcrypt.hash(password,12),role,gymId:req.user.gymId});return res.status(201).json({ok:true})}catch(e){if(e.code===11000)return res.status(409).json({error:'This email is already registered.'});throw e}});
app.get('/api/gym',auth,async(req,res)=>{const row=await State.findOne({gymId:req.user.gymId}).lean();res.json({data:row.payload,version:row.version})});
app.post('/api/gym',auth,async(req,res)=>{const body=req.body;if(!body||typeof body.action!=='string')return res.status(400).json({error:'Invalid request'});if(req.user.role!=='Admin'&&['delete','restore','settings','plan'].includes(body.action))return res.status(403).json({error:'Administrator access is required.'});const row=await State.findOne({gymId:req.user.gymId}).lean();if(row.version!==body.version)return res.status(409).json({error:'Data changed in another window. Reload and retry.'});let data;try{data=applyMutation(row.payload,body)}catch(e){return res.status(400).json({error:e.message})}if(Buffer.byteLength(JSON.stringify(data))>12*1024*1024)return res.status(413).json({error:'Workspace size limit reached. Archive historical data before continuing.'});const updated=await State.findOneAndUpdate({gymId:req.user.gymId,version:row.version},{$set:{payload:data},$inc:{version:1}},{new:true}).lean();if(!updated)return res.status(409).json({error:'Another edit was saved. Reload and retry.'});res.json({data:updated.payload,version:updated.version})});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:2*1024*1024,files:1},fileFilter:(_req,file,cb)=>cb(null,['image/jpeg','image/png','image/webp'].includes(file.mimetype))});
app.post('/api/photo',auth,upload.single('photo'),async(req,res)=>{const f=req.file;if(!f)return res.status(400).json({error:'Choose a JPG, PNG or WebP image under 2 MB.'});const b=f.buffer;const valid=f.mimetype==='image/jpeg'?b[0]===255&&b[1]===216:f.mimetype==='image/png'?b[0]===137&&b[1]===80:b[0]===82&&b[8]===87;if(!valid)return res.status(400).json({error:'Invalid image file'});const stream=bucket.openUploadStream(randomUUID(),{metadata:{gymId:req.user.gymId,contentType:f.mimetype}});stream.once('error',()=>res.status(500).json({error:'Could not upload this image.'}));stream.once('finish',()=>res.json({url:'/api/photo?key='+stream.id}));stream.end(b)});
app.get('/api/photo',auth,async(req,res)=>{if(!mongoose.isValidObjectId(req.query.key))return res.sendStatus(404);const id=new mongoose.Types.ObjectId(req.query.key);const file=await bucket.find({_id:id,'metadata.gymId':req.user.gymId}).next();if(!file)return res.sendStatus(404);res.type(file.metadata.contentType);bucket.openDownloadStream(id).on('error',()=>res.destroy()).pipe(res)});
app.get('/api/health',(_req,res)=>res.json({status:mongoose.connection.readyState===1?'ok':'unavailable'}));
app.use('/api',(_req,res)=>res.status(404).json({error:'Endpoint not found'}));
const clientPath=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../standalone-dist');
app.use(express.static(clientPath));app.get('/{*path}',(_req,res)=>res.sendFile(path.join(clientPath,'index.html')));
app.use((err,req,res,_next)=>{console.error('Request failed:',err.name);if(res.headersSent)return;res.status(err.status===413?413:err instanceof multer.MulterError||err.type==='entity.parse.failed'?400:500).json({error:err.status===413?'Request is too large.':err instanceof multer.MulterError?'Image must be under 2 MB.':err.type==='entity.parse.failed'?'Invalid JSON request.':'Something went wrong. Please try again.'})});
const server=app.listen(Number(process.env.PORT||3000),()=>console.log('Ironpulse is ready on port '+(process.env.PORT||3000)));
async function shutdown(){server.close(async()=>{await mongoose.disconnect();process.exit(0)});setTimeout(()=>process.exit(1),10000).unref()};process.once('SIGTERM',shutdown);process.once('SIGINT',shutdown);
