import { stateSchema, memberSchema, paymentSchema, planSchema, balance, day, status, cents, addMonths } from './gym.ts';
export function applyMutation(input:unknown,body:any){
let data=stateSchema.parse(input);let log='';const id=crypto.randomUUID();
if(body.action==='member'){const m=memberSchema.parse({...body.value,id:body.value.id||id});if(m.end<m.start)throw Error('End date must follow the start date');if(!data.plans.some(p=>p.id===m.planId))throw Error('Select a valid plan');if(data.members.some(x=>x.email===m.email&&x.id!==m.id))throw Error('A member with this email already exists');if(cents(m.fee)<data.payments.filter(p=>p.memberId===m.id).reduce((s,p)=>s+cents(p.amount),0))throw Error('Fee cannot be lower than payments already recorded');const exists=data.members.some(x=>x.id===m.id);data.members=exists?data.members.map(x=>x.id===m.id?m:x):[m,...data.members];log=(exists?'Updated ':'Added ')+m.name;}
else if(body.action==='delete'){const m=data.members.find(x=>x.id===body.id);if(!m)throw Error('Member not found');data.members=data.members.filter(x=>x.id!==m.id);data.payments=data.payments.filter(x=>x.memberId!==m.id);data.attendance=data.attendance.filter(x=>x.memberId!==m.id);log='Deleted member '+m.name+' and associated records';}
else if(body.action==='payment'){const p=paymentSchema.parse({...body.value,id});if(!data.members.some(x=>x.id===p.memberId))throw Error('Member not found');if(p.amount>balance(data,p.memberId))throw Error('Payment exceeds the outstanding balance');if(p.date>day())throw Error('Payment date cannot be in the future');data.payments.unshift(p);log='Recorded payment of ₹'+p.amount;}
else if(body.action==='plan'){const editing=!!body.value.id;const p=planSchema.parse({...body.value,id:body.value.id||id});if(editing&&!data.plans.some(x=>x.id===p.id))throw Error('Plan not found');if(data.plans.some(x=>x.id!==p.id&&x.name.toLowerCase()===p.name.toLowerCase()))throw Error('A plan with this name already exists');data.plans=editing?data.plans.map(x=>x.id===p.id?p:x):[...data.plans,p];log=(editing?'Updated ':'Created ')+p.name+' plan';}
else if(body.action==='renew'){const m=data.members.find(x=>x.id===body.id);if(!m)throw Error('Member not found');const p=data.plans.find(x=>x.id===body.value.planId);if(!p)throw Error('Select a valid plan');const start=body.value.start;const end=addMonths(start,p.months);if(start<=m.end)throw Error('Renewal must start after the current membership ends');const nextDay=new Date(new Date(m.end+'T00:00:00Z').getTime()+86400000).toISOString().slice(0,10);if(m.end>=day()&&start!==nextDay)throw Error('An active membership must renew on the next day after its current end date');const updated=memberSchema.parse({...m,planId:p.id,start:m.end>=day()?m.start:start,end,due:body.value.due,fee:(cents(m.fee)+cents(p.price))/100});data.members=data.members.map(x=>x.id===m.id?updated:x);log='Renewed '+m.name+' from '+start+' to '+end+'; added fee ₹'+p.price;}

else if(body.action==='attendance'){const m=data.members.find(x=>x.id===body.id);if(!m||status(m)!=='Active')throw Error('Only active members can check in');if(data.attendance.some(a=>a.memberId===m.id&&a.date===day()))throw Error('Already checked in today');data.attendance.unshift({id,memberId:m.id,date:day(),time:new Date().toISOString().slice(11,16)});log=m.name+' checked in';}
else if(body.action==='settings'){data.settings=stateSchema.shape.settings.parse(body.value);log='Updated gym settings';}
else if(body.action==='restore'){data=stateSchema.parse(body.value);for(const key of ['members','plans','payments','attendance'] as const){if(new Set(data[key].map(x=>x.id)).size!==data[key].length)throw Error('Backup has duplicate records');}if(data.members.some(m=>!data.plans.some(p=>p.id===m.planId)||m.end<m.start)||[...data.payments,...data.attendance].some(x=>!data.members.some(m=>m.id===x.memberId)))throw Error('Backup contains invalid references');if(data.members.some(m=>data.payments.filter(p=>p.memberId===m.id).reduce((n,p)=>n+cents(p.amount),0)>cents(m.fee)))throw Error('Backup payments exceed membership fees');if(new Set(data.attendance.map(a=>a.memberId+'|'+a.date)).size!==data.attendance.length)throw Error('Backup has duplicate daily check-ins');log='Restored gym backup';}
else if(body.action==='reminder'){if(!data.members.some(x=>x.id===body.id))throw Error('Member not found');log='Prepared '+String(body.channel).slice(0,20)+' reminder preview (not sent)';}
else throw Error('Unknown operation');
data.logs.unshift({id:crypto.randomUUID(),text:log,time:new Date().toISOString()});data.logs=data.logs.slice(0,500);
return stateSchema.parse(data);
}
