const unsignedWindows=process.env.IRONPULSE_UNSIGNED_WINDOWS==='1';
module.exports={
 appId:'com.ironpulse.gym',productName:'Ironpulse Gym Management',directories:{app:'desktop-stage',output:'client-installers'},
 electronVersion:'44.1.0',asar:true,npmRebuild:false,forceCodeSigning:!unsignedWindows,
 beforePack:async context=>{if(unsignedWindows&&context.electronPlatformName!=='win32')throw Error('Unsigned opt-in is Windows-only');const fs=require('node:fs');const path=require('node:path');const {auditDirectory}=await import(require('node:url').pathToFileURL(path.join(context.packager.projectDir,'desktop/audit-package.mjs')).href);auditDirectory(path.join(context.packager.projectDir,'desktop-stage'));const info=JSON.parse(fs.readFileSync(path.join(context.packager.projectDir,'desktop-stage/package.json'),'utf8')).ironpulseBuild;const targetArch={0:'ia32',1:'x64',2:'armv7l',3:'arm64',4:'universal'}[context.arch];if(!info||info.platform!==context.electronPlatformName||info.arch!==targetArch||info.electron!=='44.1.0')throw Error('Bytecode platform, architecture or Electron version mismatch. Run desktop:prepare on the matching native runner.');},
 files:['main.cjs','main.jsc','preload.cjs','license-public.pem','renderer/**/*','node_modules/bytenode/**/*','THIRD_PARTY_NOTICES.txt'],
 afterPack:async context=>{const path=require('node:path');const {flipFuses,FuseVersion,FuseV1Options}=require('@electron/fuses');const executable=context.electronPlatformName==='darwin'?path.join(context.appOutDir,context.packager.appInfo.productFilename+'.app','Contents','MacOS',context.packager.appInfo.productFilename):path.join(context.appOutDir,context.packager.appInfo.productFilename+'.exe');await flipFuses(executable,{version:FuseVersion.V1,[FuseV1Options.RunAsNode]:false,[FuseV1Options.EnableNodeOptionsEnvironmentVariable]:false,[FuseV1Options.EnableNodeCliInspectArguments]:false,[FuseV1Options.EnableEmbeddedAsarIntegrityValidation]:true,[FuseV1Options.OnlyLoadAppFromAsar]:true});},
 win:{signExecutable:!unsignedWindows,target:[{target:'nsis',arch:['x64']}],artifactName:unsignedWindows?'Ironpulse-Setup-${arch}.${ext}':'Ironpulse-Setup-${version}-${arch}.${ext}'},
 nsis:{oneClick:true,perMachine:false,allowElevation:false,createDesktopShortcut:true,runAfterFinish:true,deleteAppDataOnUninstall:false},
 mac:{target:['dmg'],category:'public.app-category.business',hardenedRuntime:true,entitlements:'desktop/entitlements.mac.plist',entitlementsInherit:'desktop/entitlements.mac.plist',notarize:true,artifactName:'Ironpulse-${version}-mac-${arch}.${ext}'},
 dmg:{sign:true}
};
