import React,{useEffect,useState} from 'react';
import {Dumbbell,ShieldCheck,Download,Upload} from 'lucide-react';
import GymApp from '../app/gym-app';
export default function DesktopRoot(){
 const [phase,setPhase]=useState('loading'),[error,setError]=useState(''),[request,setRequest]=useState<any>(null),[busy,setBusy]=useState(false);
 async function check(){try{const r=await fetch('/api/license');const l:any=await r.json();setRequest(l.request);if(!l.active){setPhase('activate');return}const setup:any=await (await fetch('/api/setup')).json();setPhase(setup.required?'setup':'ready')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{check();const timer=setInterval(check,30000);const expired=()=>setPhase('activate');window.addEventListener('ironpulse-license-required',expired);return()=>{clearInterval(timer);window.removeEventListener('ironpulse-license-required',expired)}},[]);
 if(phase==='ready')return <GymApp portable/>;
 return <div className="standalone-login"><aside><a className="brand"><span className="brandmark"><Dumbbell size={27}/></span><span>IRONPULSE<small>GYM MANAGEMENT</small></span></a><div><h1>Your gym.<br/>On your computer.</h1><p>Private local records.<br/>No database setup required.</p><div className="login-pill"><ShieldCheck size={18}/>Licensed for this machine</div></div><small>Activation support: contact the person who supplied your app</small></aside><section><div className="login-form-wrapper"><h1>{phase==='activate'?'Activate Ironpulse':phase==='setup'?'Create your admin account':'Opening Ironpulse…'}</h1>{error&&<div className="error" role="alert">{error}<button className="text-button" onClick={check}>Retry</button></div>}
 {phase==='activate'&&<><p>Send your activation request to the vendor. Then import the license file they send back.</p><div className="modal-form"><label>Machine code<input readOnly value={request?.machine||''}/></label><button className="secondary" disabled={!request||busy} onClick={async()=>{try{await window.ironpulse!.requestFile()}catch(e){setError((e as Error).message)}}}><Download size={16}/>Save activation request</button><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await window.ironpulse!.importLicense();if(r.error)throw Error(r.error);if(r.ok)await check()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><Upload size={16}/>Import license file</button><small>This license is tied to this Windows installation or Mac. Moving to another machine requires a new license.</small></div></>}
 {phase==='setup'&&<><p>Choose your own login. Your workspace starts empty.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{if(form.get('password')!==form.get('confirm'))throw Error('Passwords do not match');const r=await fetch('/api/setup',{method:'POST',body:JSON.stringify({name:form.get('name'),email:form.get('email'),password:form.get('password')})});const j:any=await r.json();if(!r.ok)throw Error(j.error);await check()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Your name<input name="name" minLength={2} required autoComplete="name"/></label><label>Admin email<input type="email" name="email" required autoComplete="username"/></label><label>Password (12+ characters)<input name="password" type="password" minLength={12} maxLength={128} required autoComplete="new-password"/></label><label>Confirm password<input name="confirm" type="password" required autoComplete="new-password"/></label><button className="primary" disabled={busy}>Create account</button></form></>}
 </div></section></div>;
}
